SELECT
    COMPANYCODE,
    INVOICINGPARTY AS VENDOR,
    DOCUMENTCURRENCY,
    FISCALYEAR,
    DOCUMENTDATE,
    POSTINGDATE,
    INVOICEGROSSAMOUNT,
    SUPPLIERINVOICESTATUS,
    ISINVOICE
FROM {{ source('sap_bdc_l1', 'SUPPLIERINVOICE') }}
WHERE ISINVOICE = TRUE
