SELECT
    li.COMPANYCODE,
    li.COSTCENTER,
    cc.DEPARTMENT,
    li.PROFITCENTER,
    li.GLACCOUNT,
    li.FISCALYEAR,
    li.FISCALPERIOD,
    SUM(ABS(li.AMOUNTINCOMPANYCODECURRENCY)) AS EXPENSE_AMOUNT,
    COUNT(*) AS LINE_COUNT
FROM {{ ref('stg_gl_line_items') }} li
LEFT JOIN {{ ref('stg_cost_centers') }} cc
    ON li.COSTCENTER = cc.COSTCENTER AND li.COMPANYCODE = cc.COMPANYCODE
WHERE li.DEBITCREDITCODE = 'S'
  AND (li.GLACCOUNT LIKE '5%' OR li.GLACCOUNT LIKE '6%')
  AND li.COSTCENTER != ''
GROUP BY li.COMPANYCODE, li.COSTCENTER, cc.DEPARTMENT, li.PROFITCENTER, li.GLACCOUNT, li.FISCALYEAR, li.FISCALPERIOD
