SELECT
    COMPANYCODE,
    GLACCOUNT,
    FISCALYEAR,
    FISCALPERIOD,
    DEBITCREDITCODE,
    SUM(AMOUNTINCOMPANYCODECURRENCY) AS AMOUNT,
    COUNT(*) AS LINE_COUNT
FROM {{ ref('stg_gl_line_items') }}
GROUP BY COMPANYCODE, GLACCOUNT, FISCALYEAR, FISCALPERIOD, DEBITCREDITCODE
