SELECT
    li.COMPANYCODE,
    li.FISCALYEAR,
    li.FISCALPERIOD,
    li.COMPANYCODECURRENCY,
    SUM(CASE WHEN li.GLACCOUNT LIKE '4%' AND li.DEBITCREDITCODE = 'H'
             THEN ABS(li.AMOUNTINCOMPANYCODECURRENCY) ELSE 0 END) AS REVENUE,
    SUM(CASE WHEN (li.GLACCOUNT LIKE '5%' OR li.GLACCOUNT LIKE '6%') AND li.DEBITCREDITCODE = 'S'
             THEN ABS(li.AMOUNTINCOMPANYCODECURRENCY) ELSE 0 END) AS EXPENSES,
    SUM(CASE WHEN li.GLACCOUNT LIKE '4%' AND li.DEBITCREDITCODE = 'H'
             THEN ABS(li.AMOUNTINCOMPANYCODECURRENCY) ELSE 0 END)
    - SUM(CASE WHEN (li.GLACCOUNT LIKE '5%' OR li.GLACCOUNT LIKE '6%') AND li.DEBITCREDITCODE = 'S'
             THEN ABS(li.AMOUNTINCOMPANYCODECURRENCY) ELSE 0 END) AS NET_INCOME,
    COUNT(DISTINCT li.ACCOUNTINGDOCUMENT) AS DOCUMENT_COUNT,
    COUNT(*) AS LINE_ITEM_COUNT
FROM {{ ref('stg_gl_line_items') }} li
GROUP BY li.COMPANYCODE, li.FISCALYEAR, li.FISCALPERIOD, li.COMPANYCODECURRENCY
