SELECT
    li.COMPANYCODE,
    li.PROFITCENTER,
    pc.SEGMENT,
    li.GLACCOUNT,
    li.FISCALYEAR,
    li.FISCALPERIOD,
    SUM(ABS(li.AMOUNTINCOMPANYCODECURRENCY)) AS REVENUE_AMOUNT,
    COUNT(*) AS LINE_COUNT
FROM {{ ref('stg_gl_line_items') }} li
LEFT JOIN {{ ref('stg_profit_centers') }} pc
    ON li.PROFITCENTER = pc.PROFITCENTER AND li.COMPANYCODE = pc.COMPANYCODE
WHERE li.DEBITCREDITCODE = 'H'
  AND li.GLACCOUNT LIKE '4%'
GROUP BY li.COMPANYCODE, li.PROFITCENTER, pc.SEGMENT, li.GLACCOUNT, li.FISCALYEAR, li.FISCALPERIOD
