-- =====================================================================
-- L1 (silver) — SAP BDC curated views
-- 1:1 governed views over the L0 SAP BDC Standard Data Products, with
-- business-friendly column comments. Nothing is copied; these read
-- directly from the shared SAP_BDC_DEMO_* databases.
-- Run as ACCOUNTADMIN (or a role with access to the L0 shares).
-- =====================================================================

create or replace schema SAP_FINANCE_360.SAP_BDC_L1 COMMENT='SAP BDC Layer 1 - Raw/Source Data';

create or replace view SAP_FINANCE_360.SAP_BDC_L1.COSTCENTER(
	CONTROLLINGAREA COMMENT 'Controlling area for cost accounting',
	COSTCENTER COMMENT 'Cost center identifier',
	VALIDITYENDDATE COMMENT 'End date of the cost center validity period',
	VALIDITYSTARTDATE COMMENT 'Start date of the cost center validity period',
	ISBLKDFORPRIMARYCOSTSPOSTING COMMENT 'Whether primary cost postings are blocked',
	ISBLOCKEDFORPLANPRIMARYCOSTS COMMENT 'Whether planning of primary costs is blocked',
	COMPANYCODE COMMENT 'SAP company code',
	BUSINESSAREA COMMENT 'Business area assignment',
	COSTCENTERCATEGORY COMMENT 'Cost center category (e.g. production, admin)',
	COSTCTRRESPONSIBLEPERSONNAME COMMENT 'Name of the person responsible for the cost center',
	COSTCTRRESPONSIBLEUSER COMMENT 'SAP user responsible for the cost center',
	COSTCENTERCURRENCY COMMENT 'Currency of the cost center',
	COSTINGSHEET COMMENT 'Costing sheet for overhead calculation',
	TAXJURISDICTION COMMENT 'Tax jurisdiction code',
	PROFITCENTER COMMENT 'Associated profit center',
	PLANT COMMENT 'Manufacturing plant code',
	LOGICALSYSTEM COMMENT 'SAP logical system identifier',
	COSTCENTERCREATIONDATE COMMENT 'Date the cost center was created',
	COSTCENTERCREATEDBYUSER COMMENT 'User who created the cost center',
	ISBLKDFORSECONDARYCOSTSPOSTING COMMENT 'Whether secondary cost postings are blocked',
	ISBLOCKEDFORREVENUEPOSTING COMMENT 'Whether revenue postings are blocked',
	ISBLOCKEDFORCOMMITMENTPOSTING COMMENT 'Whether commitment postings are blocked',
	ISBLOCKEDFORPLANSECONDARYCOSTS COMMENT 'Whether planning of secondary costs is blocked',
	ISBLOCKEDFORPLANREVENUES COMMENT 'Whether planning of revenues is blocked',
	COSTCENTERALLOCATIONMETHOD COMMENT 'Method for cost center allocation',
	CONSUMPTIONQTYISRECORDED COMMENT 'Whether consumption quantities are recorded',
	DEPARTMENT COMMENT 'Organizational department of the cost center',
	SUBSEQUENTCOSTCENTER COMMENT 'Subsequent/successor cost center',
	CONDITIONUSAGE COMMENT 'Condition usage indicator',
	CONDITIONAPPLICATION COMMENT 'Condition application type',
	COSTCENTERACCOUNTINGOVERHEAD COMMENT 'Overhead rate for cost center accounting',
	COUNTRY COMMENT 'Country code of the cost center location',
	FORMOFADDRESS COMMENT 'Form of address for cost center contact',
	ADDRESSNAME COMMENT 'Primary address name',
	ADDRESSADDITIONALNAME COMMENT 'Additional address name',
	COSTCENTERADDRNAME3 COMMENT 'Address name field 3',
	COSTCENTERADDRNAME4 COMMENT 'Address name field 4',
	CITYNAME COMMENT 'City name of the cost center location',
	DISTRICT COMMENT 'District of the cost center location',
	STREETADDRESSNAME COMMENT 'Street address',
	POBOX COMMENT 'Post office box number',
	POSTALCODE COMMENT 'Postal/ZIP code',
	POBOXPOSTALCODE COMMENT 'PO box postal code',
	REGION COMMENT 'Region/state code',
	LANGUAGE COMMENT 'Language key for the cost center',
	TELEBOXNUMBER COMMENT 'Telebox number',
	PHONENUMBER1 COMMENT 'Primary phone number',
	PHONENUMBER2 COMMENT 'Secondary phone number',
	FAXNUMBER COMMENT 'Fax number',
	TELETEXNUMBER COMMENT 'Teletex number',
	TELEXNUMBER COMMENT 'Telex number',
	DATACOMMUNICATIONPHONENUMBER COMMENT 'Data communication phone number',
	COSTCENTERPRINTERDESTINATION COMMENT 'Printer destination for the cost center',
	COSTCENTERSTANDARDHIERAREA COMMENT 'Standard hierarchy area assignment',
	COSTCOLLECTOR COMMENT 'Cost collector identifier',
	COSTCENTERISCOMPLETE COMMENT 'Whether the cost center master data is complete',
	ISSTATISTICALCOSTCENTER COMMENT 'Whether this is a statistical cost center',
	OBJECTINTERNALID COMMENT 'Internal object ID',
	COSTCENTERFUNCTION COMMENT 'Function of the cost center',
	COSTCENTERALTERNATIVEFUNCTION COMMENT 'Alternative function assignment',
	FUNCTIONALAREA COMMENT 'Functional area for government reporting',
	ACTYINDEPFORMULAPLANNINGTMPL COMMENT 'Activity-independent formula planning template',
	ACTYDEPDNTFORMULAPLANNINGTMPL COMMENT 'Activity-dependent formula planning template',
	ACTYINDEPENDENTALLOCATIONTMPL COMMENT 'Activity-independent allocation template',
	ACTYDEPENDENTALLOCATIONTMPL COMMENT 'Activity-dependent allocation template',
	ACTLINDEPSTATISTICALKEYFIGURES COMMENT 'Actual independent statistical key figures',
	ACTLDEPSTATISTICALKEYFIGURES COMMENT 'Actual dependent statistical key figures',
	JOINTVENTURE COMMENT 'Joint venture assignment',
	JOINTVENTURERECOVERYCODE COMMENT 'Joint venture cost recovery code',
	JOINTVENTUREEQUITYTYPE COMMENT 'Joint venture equity type',
	JOINTVENTUREOBJECTTYPE COMMENT 'Joint venture object type',
	JOINTVENTURECLASS COMMENT 'Joint venture class',
	JOINTVENTURESUBCLASS COMMENT 'Joint venture subclass',
	BUDGETCARRYINGCOSTCENTER COMMENT 'Budget carrying cost center',
	AVAILABILITYCONTROLPROFILE COMMENT 'Availability control profile',
	AVAILABILITYCONTROLISACTIVE COMMENT 'Whether availability control is active',
	FUND COMMENT 'Fund identifier',
	GRANTID COMMENT 'Grant identifier',
	FUNDISFIXASSIGNED COMMENT 'Whether the fund is fixedly assigned',
	GRANTIDISFIXASSIGNED COMMENT 'Whether the grant is fixedly assigned',
	FUNCTIONALAREAISFIXASSIGNED COMMENT 'Whether the functional area is fixedly assigned',
	COSTCENTERCREATIONTIME COMMENT 'Time the cost center was created',
	COSTCENTERLASTCHANGEDBYUSER COMMENT 'User who last changed the cost center',
	COSTCENTERLASTCHANGEDONDATE COMMENT 'Date of the last change to the cost center',
	COSTCENTERLASTCHANGEDATTIME COMMENT 'Time of the last change',
	_COSTCENTERCATEGORY COMMENT 'Internal cost center category reference',
	_COSTCENTERHIERARCHYNODE COMMENT 'Cost center hierarchy node assignment',
	_TEXT COMMENT 'Cost center text description'
) as
SELECT * FROM SAP_BDC_DEMO_COST_CENTER.BDCCONNECT.COSTCENTER;
create or replace view SAP_FINANCE_360.SAP_BDC_L1.GENERALLEDGERACCOUNT(
	CHARTOFACCOUNTS COMMENT 'Chart of accounts key (e.g. CAUS, INT)',
	GLACCOUNT COMMENT 'General ledger account number',
	ISBALANCESHEETACCOUNT COMMENT 'Whether this is a balance sheet account',
	GLACCOUNTGROUP COMMENT 'GL account group for classification',
	CORPORATEGROUPCHARTOFACCOUNTS COMMENT 'Chart of accounts for corporate group consolidation',
	CORPORATEGROUPACCOUNT COMMENT 'Corporate group account number',
	PROFITLOSSACCOUNTTYPE COMMENT 'Profit and loss account type (revenue, expense, etc.)',
	SAMPLEGLACCOUNT COMMENT 'Sample/template GL account used for creation',
	ACCOUNTISMARKEDFORDELETION COMMENT 'Whether the account is flagged for deletion',
	ACCOUNTISBLOCKEDFORCREATION COMMENT 'Whether new master data creation is blocked',
	ACCOUNTISBLOCKEDFORPOSTING COMMENT 'Whether postings to this account are blocked',
	ACCOUNTISBLOCKEDFORPLANNING COMMENT 'Whether planning entries are blocked',
	PARTNERCOMPANY COMMENT 'Trading partner company code',
	FUNCTIONALAREA COMMENT 'Functional area assignment',
	CREATIONDATE COMMENT 'Date the GL account master was created',
	CREATEDBYUSER COMMENT 'User who created the GL account',
	LASTCHANGEDATETIME COMMENT 'Timestamp of last change to the account master',
	GLACCOUNTTYPE COMMENT 'GL account type (X=balance sheet, N=P&L, etc.)',
	GLACCOUNTSUBTYPE COMMENT 'GL account subtype for further classification',
	GLACCOUNTEXTERNAL COMMENT 'External GL account number',
	BANKRECONCILIATIONACCOUNT COMMENT 'Bank reconciliation account number',
	ISPROFITLOSSACCOUNT COMMENT 'Whether this is a profit and loss account',
	_CHARTOFACCOUNTS COMMENT 'Internal chart of accounts reference',
	_CHARTOFACCOUNTSTEXT COMMENT 'Text description of the chart of accounts',
	_CORPORATEGROUPCHARTOFACCOUNTS COMMENT 'Internal corporate group chart of accounts reference',
	_GLACCOUNTHIERARCHYNODE COMMENT 'GL account hierarchy node assignment'
) as
SELECT * FROM SAP_BDC_DEMO_GENERAL_LEDGER_ACCOUNT.BDCCONNECT.GENERALLEDGERACCOUNT;
create or replace view SAP_FINANCE_360.SAP_BDC_L1.JOURNALENTRY(
	COMPANYCODE COMMENT 'SAP company code identifier',
	FISCALYEAR COMMENT 'Fiscal year of the journal entry',
	ACCOUNTINGDOCUMENT COMMENT 'Unique accounting document number',
	ACCOUNTINGDOCUMENTTYPE COMMENT 'Type of accounting document (e.g. SA, AB, KR)',
	DOCUMENTDATE COMMENT 'Date on the original document',
	POSTINGDATE COMMENT 'Date the entry was posted to the ledger',
	FISCALPERIOD COMMENT 'Fiscal period within the fiscal year',
	ACCOUNTINGDOCUMENTCREATIONDATE COMMENT 'Date the accounting document was created in SAP',
	CREATIONTIME COMMENT 'Time the accounting document was created',
	LASTMANUALCHANGEDATE COMMENT 'Date of last manual change to the document',
	LASTAUTOMATICCHANGEDATE COMMENT 'Date of last automatic/system change',
	LASTCHANGEDATE COMMENT 'Date of most recent change of any kind',
	EXCHANGERATEDATE COMMENT 'Date used for exchange rate determination',
	ACCOUNTINGDOCCREATEDBYUSER COMMENT 'SAP user who created the accounting document',
	TRANSACTIONCODE COMMENT 'SAP transaction code used to create the entry',
	INTERCOMPANYTRANSACTION COMMENT 'Intercompany transaction reference number',
	DOCUMENTREFERENCEID COMMENT 'Reference document ID from originating transaction',
	RECURRINGACCOUNTINGDOCUMENT COMMENT 'Recurring document template number',
	RECRRGJOURNALENTRYCOMPANYCODE COMMENT 'Company code of the recurring journal entry template',
	RECRRGJOURNALENTRYFISCALYEAR COMMENT 'Fiscal year of the recurring journal entry template',
	REVERSEDOCUMENT COMMENT 'Reversal document number if this entry was reversed',
	REVERSEDOCUMENTFISCALYEAR COMMENT 'Fiscal year of the reversal document',
	ACCOUNTINGDOCUMENTHEADERTEXT COMMENT 'Free-text description in the document header',
	TRANSACTIONCURRENCY COMMENT 'Currency of the original transaction',
	ABSOLUTEEXCHANGERATE COMMENT 'Absolute exchange rate used for currency conversion',
	EXCHANGERATE COMMENT 'Exchange rate applied to the transaction',
	EXCHRATEISINDIRECTQUOTATION COMMENT 'Whether the exchange rate uses indirect quotation',
	EFFECTIVEEXCHANGERATE COMMENT 'Effective exchange rate after adjustments',
	ACCOUNTINGDOCUMENTCATEGORY COMMENT 'Category classification of the accounting document',
	NETAMOUNTISPOSTED COMMENT 'Whether the net amount method was used for posting',
	JRNLENTRYISPOSTEDTOPREVPERIOD COMMENT 'Whether the entry was posted to a previous period',
	BUSINESSTRANSACTIONTYPE COMMENT 'Business transaction type code',
	JRNLENTRYBUSINESSTRANSTYPE COMMENT 'Journal entry-specific business transaction type',
	BATCHINPUTSESSION COMMENT 'Batch input session used for mass posting',
	REFERENCEDOCUMENTTYPE COMMENT 'Type of the referenced source document',
	ORIGINALREFERENCEDOCUMENT COMMENT 'Original reference document number',
	FINANCIALMANAGEMENTAREA COMMENT 'Financial management area for funds management',
	COMPANYCODECURRENCY COMMENT 'Local currency of the company code',
	ADDITIONALCURRENCY1 COMMENT 'First additional parallel currency',
	ADDITIONALCURRENCY2 COMMENT 'Second additional parallel currency',
	REVERSALISPLANNED COMMENT 'Whether a planned reversal exists for this entry',
	PLANNEDREVERSALDATE COMMENT 'Scheduled date for the planned reversal',
	TAXISCALCULATEDAUTOMATICALLY COMMENT 'Whether tax was calculated automatically by the system',
	ADDITIONALCURRENCY1ROLE COMMENT 'Role designation of the first additional currency',
	ADDITIONALCURRENCY2ROLE COMMENT 'Role designation of the second additional currency',
	TAXBASEAMOUNTISNETAMOUNT COMMENT 'Whether the tax base amount equals the net amount',
	SOURCECOMPANYCODE COMMENT 'Source company code for cross-company postings',
	LOGICALSYSTEM COMMENT 'SAP logical system identifier',
	REFERENCEDOCUMENTLOGICALSYSTEM COMMENT 'Logical system of the referenced document',
	TAXABSOLUTEEXCHANGERATE COMMENT 'Absolute exchange rate for tax calculation',
	TAXEXCHANGERATE COMMENT 'Exchange rate used for tax amounts',
	TAXEXCHRATEISINDIRECTQUOTATION COMMENT 'Whether the tax exchange rate uses indirect quotation',
	TAXEFFECTIVEEXCHANGERATE COMMENT 'Effective exchange rate for tax calculations',
	CTRYCRCYTXABSOLUTEEXCHANGERATE COMMENT 'Country currency tax absolute exchange rate',
	CTRYCRCYTAXEFFCTVEXCHANGERATE COMMENT 'Country currency tax effective exchange rate',
	REVERSALREASON COMMENT 'Reason code for the reversal',
	PARKEDBYUSER COMMENT 'User who parked the document',
	PARKINGDATE COMMENT 'Date the document was parked',
	PARKINGTIME COMMENT 'Time the document was parked',
	PARKINGTRANSACTIONCODE COMMENT 'Transaction code used for parking',
	BRANCH COMMENT 'Branch office identifier',
	NMBROFPAGES COMMENT 'Number of pages in the original document',
	ISDISCOUNTDOCUMENT COMMENT 'Whether this is a cash discount document',
	REFERENCE1INDOCUMENTHEADER COMMENT 'First reference field in the document header',
	REFERENCE2INDOCUMENTHEADER COMMENT 'Second reference field in the document header',
	INVOICERECEIPTDATE COMMENT 'Date the invoice was received',
	LEDGER COMMENT 'Ledger identifier (e.g. 0L for leading ledger)',
	LEDGERGROUP COMMENT 'Ledger group assignment',
	ALTERNATIVEREFERENCEDOCUMENT COMMENT 'Alternative reference document number',
	TAXREPORTINGDATE COMMENT 'Date used for tax reporting purposes',
	TAXFULFILLMENTDATE COMMENT 'Date of tax fulfillment',
	ACCOUNTINGDOCUMENTCLASS COMMENT 'Class of the accounting document',
	EXCHANGERATETYPE COMMENT 'Type of exchange rate used (e.g. M for average rate)',
	MARKETDATAABSOLUTEEXCHANGERATE COMMENT 'Market data absolute exchange rate',
	MKTDATAEFFECTIVEEXCHANGERATE COMMENT 'Market data effective exchange rate',
	SENDERLOGICALSYSTEM COMMENT 'Logical system of the sending system',
	SENDERCOMPANYCODE COMMENT 'Company code in the sending system',
	SENDERACCOUNTINGDOCUMENT COMMENT 'Accounting document number in the sending system',
	SENDERFISCALYEAR COMMENT 'Fiscal year in the sending system',
	REVERSALREFERENCEDOCUMENTCNTXT COMMENT 'Context of the reversal reference document',
	REVERSALREFERENCEDOCUMENT COMMENT 'Reversal reference document number',
	LATEPAYMENTREASON COMMENT 'Reason code for late payment',
	SALESDOCUMENTCONDITION COMMENT 'Sales document condition number',
	ISREVERSAL COMMENT 'Whether this document is a reversal entry',
	ISREVERSED COMMENT 'Whether this document has been reversed',
	GLBUSINESSTRANSACTIONGROUP COMMENT 'GL business transaction group classification',
	COSTACCOUNTINGVALUATIONDATE COMMENT 'Valuation date for cost accounting',
	TAXCOUNTRY COMMENT 'Country code for tax determination',
	JOURNALENTRYLASTCHANGEDATETIME COMMENT 'Timestamp of the last change to the journal entry',
	JOURNALENTRYISSECONDARYENTRY COMMENT 'Whether this is a secondary cost entry',
	JOURNALENTRYREPROCESSINGSTATUS COMMENT 'Reprocessing status of the journal entry',
	JRNLENTRYCNTRYSPECIFICREF1 COMMENT 'Country-specific reference field 1',
	JRNLENTRYCNTRYSPECIFICDATE1 COMMENT 'Country-specific date field 1',
	JRNLENTRYCNTRYSPECIFICREF2 COMMENT 'Country-specific reference field 2',
	JRNLENTRYCNTRYSPECIFICDATE2 COMMENT 'Country-specific date field 2',
	JRNLENTRYCNTRYSPECIFICREF3 COMMENT 'Country-specific reference field 3',
	JRNLENTRYCNTRYSPECIFICDATE3 COMMENT 'Country-specific date field 3',
	JRNLENTRYCNTRYSPECIFICREF4 COMMENT 'Country-specific reference field 4',
	JRNLENTRYCNTRYSPECIFICDATE4 COMMENT 'Country-specific date field 4',
	JRNLENTRYCNTRYSPECIFICREF5 COMMENT 'Country-specific reference field 5',
	JRNLENTRYCNTRYSPECIFICDATE5 COMMENT 'Country-specific date field 5',
	JRNLENTRYCNTRYSPECIFICBP1 COMMENT 'Country-specific business partner field 1',
	JRNLENTRYCNTRYSPECIFICBP2 COMMENT 'Country-specific business partner field 2',
	WITHHOLDINGTAXREPORTINGDATE COMMENT 'Reporting date for withholding tax',
	ENTRYVIEWPOSTINGCONTROL COMMENT 'Posting control indicator for the entry view',
	ISBUDGETARYLEDGERDOC COMMENT 'Whether this is a budgetary ledger document'
) as
SELECT * FROM SAP_BDC_DEMO_JOURNAL_ENTRY_HEADER.BDCCONNECT.JOURNALENTRY;
create or replace view SAP_FINANCE_360.SAP_BDC_L1.OPERATIONALACCTGDOCITEM(
	COMPANYCODE COMMENT 'SAP company code identifier',
	ACCOUNTINGDOCUMENT COMMENT 'Accounting document number',
	FISCALYEAR COMMENT 'Fiscal year of the document',
	ACCOUNTINGDOCUMENTITEM COMMENT 'Line item number within the accounting document',
	CHARTOFACCOUNTS COMMENT 'Chart of accounts key (e.g. CAUS, INT)',
	ACCOUNTINGDOCUMENTITEMTYPE COMMENT 'Type classification of the line item',
	CLEARINGDATE COMMENT 'Date the open item was cleared',
	CLEARINGCREATIONDATE COMMENT 'Date the clearing document was created',
	CLEARINGJOURNALENTRYFISCALYEAR COMMENT 'Fiscal year of the clearing journal entry',
	CLEARINGDOCFISCALYEAR COMMENT 'Fiscal year of the clearing document',
	CLEARINGJOURNALENTRY COMMENT 'Clearing journal entry document number',
	CLEARINGACCOUNTINGDOCUMENT COMMENT 'Clearing accounting document number',
	POSTINGKEY COMMENT 'Posting key determining debit/credit and account type',
	FINANCIALACCOUNTTYPE COMMENT 'Type of financial account (GL, customer, vendor)',
	SPECIALGLCODE COMMENT 'Special GL indicator code',
	SPECIALGLTRANSACTIONTYPE COMMENT 'Special GL transaction type',
	TARGETSPECIALGLCODE COMMENT 'Target special GL indicator',
	DEBITCREDITCODE COMMENT 'Debit (S) or Credit (H) indicator',
	BUSINESSAREA COMMENT 'Business area for internal reporting segmentation',
	PARTNERBUSINESSAREA COMMENT 'Business area of the trading partner',
	TAXCODE COMMENT 'Tax code for VAT/sales tax determination',
	TAXCOUNTRY COMMENT 'Country code for tax jurisdiction',
	TAXRATEVALIDITYSTARTDATE COMMENT 'Start date for the applicable tax rate',
	WITHHOLDINGTAXCODE COMMENT 'Withholding tax code',
	TAXTYPE COMMENT 'Type of tax applied',
	TAXITEMGROUP COMMENT 'Tax item group classification',
	TRANSACTIONTYPEDETERMINATION COMMENT 'Transaction type determination method',
	VALUEDATE COMMENT 'Value date for interest calculation',
	ASSIGNMENTREFERENCE COMMENT 'Assignment reference field for sorting and matching',
	DOCUMENTITEMTEXT COMMENT 'Free-text description of the line item',
	INTERESTCALCULATIONBLOCKREASON COMMENT 'Reason code for blocking interest calculation',
	PARTNERCOMPANY COMMENT 'Trading partner company code',
	FINANCIALTRANSACTIONTYPE COMMENT 'Financial transaction type code',
	CORPORATEGROUPACCOUNT COMMENT 'Corporate group consolidation account',
	PLANNINGLEVEL COMMENT 'Planning level for budgeting',
	CONTROLLINGAREA COMMENT 'Controlling area for cost accounting',
	COSTCENTER COMMENT 'Cost center for expense allocation',
	PROJECT COMMENT 'Project number (WBS element)',
	ORDERID COMMENT 'Internal order number',
	BILLINGDOCUMENT COMMENT 'Billing document number from SD',
	SALESDOCUMENT COMMENT 'Sales document number',
	SALESDOCUMENTITEM COMMENT 'Sales document item number',
	SCHEDULELINE COMMENT 'Schedule line number',
	SERVICEDOCUMENTTYPE COMMENT 'Service document type',
	SERVICEDOCUMENT COMMENT 'Service document number',
	SERVICEDOCUMENTITEM COMMENT 'Service document item number',
	MASTERFIXEDASSET COMMENT 'Master fixed asset number',
	FIXEDASSET COMMENT 'Fixed asset sub-number',
	ASSETTRANSACTIONTYPE COMMENT 'Asset transaction type code',
	ASSETVALUEDATE COMMENT 'Value date for asset posting',
	PERSONNELNUMBER COMMENT 'HR personnel number',
	ISSALESRELATED COMMENT 'Whether the item is related to a sales transaction',
	LINEITEMDISPLAYISENABLED COMMENT 'Whether line item display is enabled for this account',
	ISOPENITEMMANAGED COMMENT 'Whether the account uses open item management',
	ADDRESSANDBANKISSETMANUALLY COMMENT 'Whether address and bank data was set manually',
	DOWNPAYMENTISNETPROCEDURE COMMENT 'Whether net procedure is used for down payments',
	ISNOTCASHDISCOUNTLIABLE COMMENT 'Whether the item is excluded from cash discount',
	SUPLRINVCISCAPITALGOODSRELATED COMMENT 'Whether the supplier invoice relates to capital goods',
	ISAUTOMATICALLYCREATED COMMENT 'Whether the line item was auto-generated',
	ISUSEDINPAYMENTTRANSACTION COMMENT 'Whether the item is used in payment transactions',
	OPERATIONALGLACCOUNT COMMENT 'Operational GL account number',
	GLACCOUNT COMMENT 'General ledger account number',
	CUSTOMER COMMENT 'Customer account number',
	SUPPLIER COMMENT 'Supplier/vendor account number',
	BRANCHACCOUNT COMMENT 'Branch account identifier',
	ISBALANCESHEETACCOUNT COMMENT 'Whether the GL account is a balance sheet account',
	PROFITLOSSACCOUNTTYPE COMMENT 'Profit and loss account type classification',
	SPECIALGLACCOUNTASSIGNMENT COMMENT 'Special GL account assignment indicator',
	DUECALCULATIONBASEDATE COMMENT 'Base date for due date calculation',
	PAYMENTTERMS COMMENT 'Payment terms key',
	CASHDISCOUNT1DAYS COMMENT 'Number of days for first cash discount period',
	CASHDISCOUNT2DAYS COMMENT 'Number of days for second cash discount period',
	NETPAYMENTDAYS COMMENT 'Number of days for net payment',
	CASHDISCOUNT1PERCENT COMMENT 'Percentage for first cash discount',
	CASHDISCOUNT2PERCENT COMMENT 'Percentage for second cash discount',
	PAYMENTMETHOD COMMENT 'Payment method key (e.g. check, wire transfer)',
	PAYMENTBLOCKINGREASON COMMENT 'Reason for blocking payment',
	FIXEDCASHDISCOUNT COMMENT 'Fixed cash discount indicator',
	HOUSEBANK COMMENT 'House bank identifier',
	BPBANKACCOUNTINTERNALID COMMENT 'Business partner bank account internal ID',
	TAXDISTRIBUTIONCODE1 COMMENT 'First tax distribution code',
	TAXDISTRIBUTIONCODE2 COMMENT 'Second tax distribution code',
	TAXDISTRIBUTIONCODE3 COMMENT 'Third tax distribution code',
	INVOICEREFERENCE COMMENT 'Invoice reference document number',
	INVOICEREFERENCEFISCALYEAR COMMENT 'Fiscal year of the invoice reference',
	INVOICEITEMREFERENCE COMMENT 'Invoice item reference number',
	FOLLOWONDOCUMENTTYPE COMMENT 'Follow-on document type',
	ACCTGDOCITMCUSTOMSTARIFFNUMBER COMMENT 'Customs tariff number on the accounting doc item',
	ACCTGDOCITMCSTMSCLEARANCEDATE COMMENT 'Customs clearance date',
	STATECENTRALBANKPAYMENTREASON COMMENT 'Central bank payment reason code',
	SUPPLYINGCOUNTRY COMMENT 'Country of supply for tax purposes',
	RECRRGSUPLRINVCISSRVCINVOICE COMMENT 'Whether recurring supplier invoice is a service invoice',
	INVOICELIST COMMENT 'Invoice list number',
	BILLOFEXCHANGEUSAGEDOCUMENT COMMENT 'Bill of exchange usage document',
	BILLOFEXCHANGEUSAGE COMMENT 'Bill of exchange usage code',
	BILLOFEXCHANGEPAYMENTREQUEST COMMENT 'Bill of exchange payment request number',
	BOEPAYMENTREQUESTFISCALYEAR COMMENT 'Fiscal year of the BOE payment request',
	BOEPAYMENTREQUESTCOMPANYCODE COMMENT 'Company code of the BOE payment request',
	DUNNINGKEY COMMENT 'Dunning key for controlling dunning behavior',
	DUNNINGBLOCKINGREASON COMMENT 'Reason for blocking dunning',
	LASTDUNNINGDATE COMMENT 'Date of the last dunning run',
	DUNNINGLEVEL COMMENT 'Current dunning level',
	DUNNINGAREA COMMENT 'Dunning area identifier',
	PAYTSLIPWTHREFSUBSCRIBER COMMENT 'Payment slip with reference - subscriber',
	PAYTSLIPWTHREFREFERENCE COMMENT 'Payment slip with reference - reference number',
	PAYTSLIPWTHREFCHECKDIGIT COMMENT 'Payment slip with reference - check digit',
	WITHHOLDINGTAXCERTIFICATE COMMENT 'Withholding tax certificate number',
	MATERIAL COMMENT 'Material number',
	PRODUCT COMMENT 'Product identifier',
	PLANT COMMENT 'Plant/manufacturing facility code',
	PURCHASINGDOCUMENT COMMENT 'Purchase order number',
	PURCHASINGDOCUMENTITEM COMMENT 'Purchase order item number',
	ACCOUNTASSIGNMENTNUMBER COMMENT 'Account assignment sequential number',
	ISCOMPLETELYDELIVERED COMMENT 'Whether the item has been completely delivered',
	MATERIALPRICECONTROL COMMENT 'Material price control indicator (S=standard, V=moving avg)',
	VALUATIONAREA COMMENT 'Valuation area for material valuation',
	INVENTORYVALUATIONTYPE COMMENT 'Inventory valuation type',
	VATREGISTRATION COMMENT 'VAT registration number',
	DELIVOFGOODSDESTCOUNTRY COMMENT 'Destination country for goods delivery',
	DELIVOFGOODSORIGINCOUNTRY COMMENT 'Country of origin for goods delivery',
	PAYMENTDIFFERENCEREASON COMMENT 'Reason code for payment differences',
	PROFITCENTER COMMENT 'Profit center for profitability reporting',
	JOINTVENTURE COMMENT 'Joint venture identifier',
	JOINTVENTURECOSTRECOVERYCODE COMMENT 'Joint venture cost recovery code',
	JOINTVENTUREEQUITYGROUP COMMENT 'Joint venture equity group',
	JOINTVENTUREPARTNER COMMENT 'Joint venture partner identifier',
	TREASURYCONTRACTTYPE COMMENT 'Treasury contract type',
	ASSETCONTRACT COMMENT 'Asset contract number',
	CASHFLOWTYPE COMMENT 'Cash flow type classification',
	TAXJURISDICTION COMMENT 'Tax jurisdiction code',
	REINTERNALFINNUMBER COMMENT 'Real estate internal finance number',
	REALESTATEOBJECT COMMENT 'Real estate object identifier',
	SETTLEMENTREFERENCEDATE COMMENT 'Reference date for settlement',
	COMMITMENTITEM COMMENT 'Commitment item for budget management',
	COMMITMENTITEMSHORTID COMMENT 'Short ID for the commitment item',
	COSTOBJECT COMMENT 'Cost object identifier',
	PROJECTNETWORK COMMENT 'Project network number',
	ORDERINTERNALBILLOFOPERATIONS COMMENT 'Order internal bill of operations',
	ORDERINTBILLOFOPERATIONSITEM COMMENT 'Order internal bill of operations item',
	WBSELEMENTINTERNALID COMMENT 'WBS element internal ID',
	PROFITABILITYSEGMENT COMMENT 'Profitability segment identifier',
	PROFITABILITYSEGMENT_2 COMMENT 'Secondary profitability segment',
	JOINTVENTUREBILLINGTYPE COMMENT 'Joint venture billing type',
	JOINTVENTUREEQUITYTYPE COMMENT 'Joint venture equity type',
	ISEUTRIANGULARDEAL COMMENT 'Whether this is an EU triangular deal',
	COSTORIGINGROUP COMMENT 'Cost origin group for cost analysis',
	COMPANYCODECURRENCYDETNMETHOD COMMENT 'Method for determining company code currency amounts',
	CLEARINGISREVERSED COMMENT 'Whether the clearing has been reversed',
	PAYMENTMETHODSUPPLEMENT COMMENT 'Supplement to the payment method',
	ALTERNATIVEGLACCOUNT COMMENT 'Alternative GL account number',
	FUNDSCENTER COMMENT 'Funds center for public sector budgeting',
	FUND COMMENT 'Fund identifier for public sector accounting',
	TAXCOMPANYCODE COMMENT 'Company code for tax reporting',
	PARTNERPROFITCENTER COMMENT 'Trading partner profit center',
	REFERENCE1IDBYBUSINESSPARTNER COMMENT 'First reference ID by business partner',
	REFERENCE2IDBYBUSINESSPARTNER COMMENT 'Second reference ID by business partner',
	EARMARKEDFUNDSDOCUMENT COMMENT 'Earmarked funds document number',
	EARMARKEDFUNDSDOCUMENTITEM COMMENT 'Earmarked funds document item number',
	ISNEGATIVEPOSTING COMMENT 'Whether this is a negative/reverse posting',
	PAYMENTCARDITEM COMMENT 'Payment card item number',
	PAYMENTCARDPAYMENTSETTLEMENT COMMENT 'Payment card settlement reference',
	CREDITCONTROLAREA COMMENT 'Credit control area for credit management',
	ALTERNATIVEPAYEEPAYER COMMENT 'Alternative payee or payer',
	REFERENCE3IDBYBUSINESSPARTNER COMMENT 'Third reference ID by business partner',
	DATAEXCHANGEINSTRUCTION1 COMMENT 'First data exchange instruction code',
	DATAEXCHANGEINSTRUCTION2 COMMENT 'Second data exchange instruction code',
	DATAEXCHANGEINSTRUCTION3 COMMENT 'Third data exchange instruction code',
	DATAEXCHANGEINSTRUCTION4 COMMENT 'Fourth data exchange instruction code',
	BPACTIVITYCODEGROSSINCOMETAX COMMENT 'Business partner activity code for gross income tax',
	REGION COMMENT 'Region/state code',
	BPEMPLOYMENTTAXDISTRTYPE COMMENT 'Business partner employment tax distribution type',
	HASPAYMENTORDER COMMENT 'Whether a payment order exists for this item',
	PAYMENTREFERENCE COMMENT 'Payment reference number',
	TAXDETERMINATIONDATE COMMENT 'Date used for tax rate determination',
	CLEARINGITEM COMMENT 'Clearing item number',
	BUSINESSPLACE COMMENT 'Business place for tax reporting (country-specific)',
	TAXSECTION COMMENT 'Tax section for tax reporting',
	COSTCTRACTIVITYTYPE COMMENT 'Cost center activity type',
	ACCOUNTSRECEIVABLEISPLEDGED COMMENT 'Whether the accounts receivable is pledged',
	ACCTSRECEIVABLEPLEDGINGCODE COMMENT 'Accounts receivable pledging code',
	BUSINESSPROCESS COMMENT 'Business process for activity-based costing',
	GRANTID COMMENT 'Grant identifier for public sector',
	FUNCTIONALAREA COMMENT 'Functional area for government reporting',
	CUSTOMERISINEXECUTION COMMENT 'Whether the customer is in execution/legal proceedings',
	FUNDEDPROGRAM COMMENT 'Funded program identifier',
	INVCITMISEXCLDFRMPROMPTPAYTACT COMMENT 'Whether invoice item is excluded from prompt payment action',
	LEDGERGLLINEITEM COMMENT 'Ledger GL line item reference',
	SEGMENT COMMENT 'Segment for segment reporting',
	PARTNERSEGMENT COMMENT 'Trading partner segment',
	PARTNERFUNCTIONALAREA COMMENT 'Trading partner functional area',
	HOUSEBANKACCOUNT COMMENT 'House bank account identifier',
	COSTELEMENT COMMENT 'Cost element (primary or secondary)',
	CLEARINGISLEDGERGROUPSPECIFIC COMMENT 'Whether clearing is ledger group specific',
	TAXITEMACCTGDOCITEMREF COMMENT 'Tax item accounting document item reference',
	PAYMENTSERVICEPROVIDER COMMENT 'Payment service provider identifier',
	PAYMENTREFBYPAYTSRVCPROVIDER COMMENT 'Payment reference by payment service provider',
	SEPAMANDATE COMMENT 'SEPA direct debit mandate reference',
	REFERENCEDOCUMENTTYPE COMMENT 'Reference document type code',
	ORIGINALREFERENCEDOCUMENT COMMENT 'Original reference document number',
	REFERENCEDOCUMENTLOGICALSYSTEM COMMENT 'Logical system of the reference document',
	ACCOUNTINGDOCUMENTITEMREF COMMENT 'Accounting document item reference',
	FISCALPERIOD COMMENT 'Fiscal period within the fiscal year',
	ACCOUNTINGDOCUMENTCATEGORY COMMENT 'Category of the accounting document',
	POSTINGDATE COMMENT 'Date the line item was posted',
	DOCUMENTDATE COMMENT 'Date on the source document',
	ACCOUNTINGDOCUMENTTYPE COMMENT 'Type of accounting document',
	NETDUEDATE COMMENT 'Net payment due date',
	CASHDISCOUNT1DUEDATE COMMENT 'Due date for first cash discount',
	CASHDISCOUNT2DUEDATE COMMENT 'Due date for second cash discount',
	OFFSETTINGACCOUNT COMMENT 'Offsetting account number',
	OFFSETTINGACCOUNTTYPE COMMENT 'Type of the offsetting account',
	OFFSETTINGCHARTOFACCOUNTS COMMENT 'Chart of accounts for the offsetting account',
	PARTNERFUND COMMENT 'Trading partner fund',
	PARTNERGRANT COMMENT 'Trading partner grant',
	BUDGETPERIOD COMMENT 'Budget period identifier',
	PARTNERBUDGETPERIOD COMMENT 'Trading partner budget period',
	BRANCHCODE COMMENT 'Branch code identifier',
	BILLINGPERIODOFPERFSTARTDATE COMMENT 'Start date of the billing performance period',
	BILLINGPERIODOFPERFENDDATE COMMENT 'End date of the billing performance period',
	JOINTVENTUREPRODUCTIONDATE COMMENT 'Joint venture production date',
	OPLACCTGDOCITMCNTRYSPCFCREF1 COMMENT 'Country-specific reference field 1 for the line item',
	PAYMENTREASON COMMENT 'Reason code for the payment',
	CASHLEDGERCOMPANYCODE COMMENT 'Company code for cash ledger',
	CASHLEDGERACCOUNT COMMENT 'Cash ledger account number',
	PUBSECBUDGETACCOUNTCOCODE COMMENT 'Public sector budget account company code',
	PUBSECBUDGETACCOUNT COMMENT 'Public sector budget account',
	FINANCIALSERVICESPRODUCTGROUP COMMENT 'Financial services product group',
	FINANCIALSERVICESBRANCH COMMENT 'Financial services branch',
	FINANCIALDATASOURCE COMMENT 'Source of the financial data',
	CUSTOMERGROUP COMMENT 'Customer group classification',
	CUSTOMERSUPPLIERCOUNTRY COMMENT 'Country of the customer or supplier',
	CUSTOMERSUPPLIERINDUSTRY COMMENT 'Industry classification of the customer or supplier',
	COMPANYCODECURRENCY COMMENT 'Local currency of the company code',
	AMOUNTINCOMPANYCODECURRENCY COMMENT 'Amount in company code (local) currency',
	FUNCTIONALCURRENCY COMMENT 'Functional currency code',
	AMOUNTINFUNCTIONALCURRENCY COMMENT 'Amount in functional currency',
	TAXAMOUNTINCOCODECRCY COMMENT 'Tax amount in company code currency',
	TAXBASEAMOUNTINCOCODECRCY COMMENT 'Tax base amount in company code currency',
	VALUATIONDIFFAMTINCOCODECRCY COMMENT 'Valuation difference amount in company code currency',
	CASHDISCOUNTAMTINCOCODECRCY COMMENT 'Cash discount amount in company code currency',
	TAXBRKDWNAMOUNT1INCOCODECRCY COMMENT 'First tax breakdown amount in company code currency',
	TAXBRKDWNAMOUNT2INCOCODECRCY COMMENT 'Second tax breakdown amount in company code currency',
	TAXBRKDWNAMOUNT3INCOCODECRCY COMMENT 'Third tax breakdown amount in company code currency',
	NONDCBLTAXAMOUNTINCOCODECRCY COMMENT 'Non-deductible tax amount in company code currency',
	INVOICEAMTINCOCODECRCY COMMENT 'Invoice amount in company code currency',
	TRANSACTIONCURRENCY COMMENT 'Currency of the original transaction',
	AMOUNTINTRANSACTIONCURRENCY COMMENT 'Amount in the original transaction currency',
	ORIGINALTAXBASEAMOUNT COMMENT 'Original tax base amount',
	TAXAMOUNT COMMENT 'Tax amount in transaction currency',
	TAXBASEAMOUNTINTRANSCRCY COMMENT 'Tax base amount in transaction currency',
	WITHHOLDINGTAXBASEAMOUNT COMMENT 'Withholding tax base amount',
	PLANNEDAMTINTRANSACTIONCRCY COMMENT 'Planned amount in transaction currency',
	CASHDISCOUNTBASEAMOUNT COMMENT 'Cash discount base amount',
	CASHDISCOUNTAMOUNT COMMENT 'Cash discount amount in transaction currency',
	NETPAYMENTAMOUNT COMMENT 'Net payment amount after discounts',
	TAXBRKDWNAMOUNT1INTRANSCRCY COMMENT 'First tax breakdown amount in transaction currency',
	TAXBRKDWNAMOUNT2INTRANSCRCY COMMENT 'Second tax breakdown amount in transaction currency',
	TAXBRKDWNAMOUNT3INTRANSCRCY COMMENT 'Third tax breakdown amount in transaction currency',
	WITHHOLDINGTAXAMOUNT COMMENT 'Withholding tax amount',
	WITHHOLDINGTAXEXEMPTIONAMT COMMENT 'Withholding tax exemption amount',
	NONDCBLTAXAMOUNTINTRANSCRCY COMMENT 'Non-deductible tax amount in transaction currency',
	INVOICEAMOUNTINFRGNCURRENCY COMMENT 'Invoice amount in foreign currency',
	BALANCETRANSACTIONCURRENCY COMMENT 'Balance transaction currency',
	AMOUNTINBALANCETRANSACCRCY COMMENT 'Amount in balance transaction currency',
	ADDITIONALCURRENCY1 COMMENT 'First additional parallel currency code',
	VALUATIONDIFFAMTINADDLCRCY1 COMMENT 'Valuation difference in first additional currency',
	AMOUNTINADDITIONALCURRENCY1 COMMENT 'Amount in first additional currency',
	TAXAMOUNTINADDITIONALCURRENCY1 COMMENT 'Tax amount in first additional currency',
	ADDITIONALCURRENCY2 COMMENT 'Second additional parallel currency code',
	AMOUNTINADDITIONALCURRENCY2 COMMENT 'Amount in second additional currency',
	TAXAMOUNTINADDITIONALCURRENCY2 COMMENT 'Tax amount in second additional currency',
	VALUATIONDIFFAMTINADDLCRCY2 COMMENT 'Valuation difference in second additional currency',
	PAYMENTCURRENCY COMMENT 'Currency used for payment',
	AMOUNTINPAYMENTCURRENCY COMMENT 'Amount in payment currency',
	CREDITCONTROLAREACURRENCY COMMENT 'Currency of the credit control area',
	HEDGEDAMOUNT COMMENT 'Hedged amount for foreign currency exposure',
	BASEUNIT COMMENT 'Base unit of measure',
	QUANTITY COMMENT 'Quantity in base unit',
	GOODSMOVEMENTENTRYUNIT COMMENT 'Unit of measure for goods movement entry',
	QUANTITYINENTRYUNIT COMMENT 'Quantity in entry unit of measure',
	PURCHASINGDOCUMENTPRICEUNIT COMMENT 'Price unit from the purchasing document',
	PURCHASEORDERQTY COMMENT 'Purchase order quantity',
	MATERIALPRICEUNITQTY COMMENT 'Material price unit quantity',
	ABSOLUTEAMOUNTINCOCODECRCY COMMENT 'Absolute amount in company code currency',
	ABSOLUTEAMOUNTINTRANSACCRCY COMMENT 'Absolute amount in transaction currency',
	ABSLTAMTINADDITIONALCURRENCY1 COMMENT 'Absolute amount in first additional currency',
	ABSLTAMTINADDITIONALCURRENCY2 COMMENT 'Absolute amount in second additional currency',
	ABSLTAMTINBALANCETRANSACCRCY COMMENT 'Absolute amount in balance transaction currency',
	ABSLTAMTINFUNCTIONALCURRENCY COMMENT 'Absolute amount in functional currency',
	ABSLTAMOUNTINPAYMENTCURRENCY COMMENT 'Absolute amount in payment currency',
	HEDGEDABSOLUTEAMOUNT COMMENT 'Hedged absolute amount',
	PLANNEDABSLTAMTINTRANSCRCY COMMENT 'Planned absolute amount in transaction currency',
	CASHDISCABSLTAMTINCOCODECRCY COMMENT 'Cash discount absolute amount in company code currency',
	CASHDISCOUNTABSOLUTEAMOUNT COMMENT 'Cash discount absolute amount in transaction currency',
	CASHDISCOUNTABSOLUTEBASEAMOUNT COMMENT 'Cash discount absolute base amount',
	INVOICEABSLTAMTINCOCODECRCY COMMENT 'Invoice absolute amount in company code currency',
	INVOICEABSLTAMTINFRGNCURRENCY COMMENT 'Invoice absolute amount in foreign currency',
	NETPAYMENTABSOLUTEAMOUNT COMMENT 'Net payment absolute amount',
	NONDCBLTAXABSLTAMTINCOCODECRCY COMMENT 'Non-deductible tax absolute amount in company code currency',
	NONDCBLTAXABSLTAMTINTRANSCRCY COMMENT 'Non-deductible tax absolute amount in transaction currency',
	TAXABSLTAMOUNTINCOCODECRCY COMMENT 'Tax absolute amount in company code currency',
	TAXABSOLUTEAMOUNT COMMENT 'Tax absolute amount in transaction currency',
	TAXABSLTAMTINADDLCURRENCY1 COMMENT 'Tax absolute amount in first additional currency',
	TAXABSLTAMTINADDLCURRENCY2 COMMENT 'Tax absolute amount in second additional currency',
	TAXABSLTBASEAMOUNTINCOCODECRCY COMMENT 'Tax absolute base amount in company code currency',
	TAXABSLTBASEAMOUNTINTRANSCRCY COMMENT 'Tax absolute base amount in transaction currency',
	ORIGLTXABSLTBASEAMOUNTINCCCRCY COMMENT 'Original tax absolute base amount in company code currency',
	ORIGINALTAXABSOLUTEBASEAMOUNT COMMENT 'Original tax absolute base amount',
	ORIGLTXABSLTBASEAMTINADDLCRCY1 COMMENT 'Original tax absolute base amount in first additional currency',
	ORIGLTXABSLTBASEAMTINADDLCRCY2 COMMENT 'Original tax absolute base amount in second additional currency',
	TAXBRKDWNABSLTAMT1INCOCODECRCY COMMENT 'First tax breakdown absolute amount in company code currency',
	TAXBRKDWNABSLTAMT2INCOCODECRCY COMMENT 'Second tax breakdown absolute amount in company code currency',
	TAXBRKDWNABSLTAMT3INCOCODECRCY COMMENT 'Third tax breakdown absolute amount in company code currency',
	TAXBRKDWNABSLTAMT1INTRANSCRCY COMMENT 'First tax breakdown absolute amount in transaction currency',
	TAXBRKDWNABSLTAMT2INTRANSCRCY COMMENT 'Second tax breakdown absolute amount in transaction currency',
	TAXBRKDWNABSLTAMT3INTRANSCRCY COMMENT 'Third tax breakdown absolute amount in transaction currency',
	WITHHOLDINGTAXABSOLUTEAMOUNT COMMENT 'Withholding tax absolute amount',
	WITHHOLDINGTAXABSOLUTEBASEAMT COMMENT 'Withholding tax absolute base amount',
	WHLDGTAXEXEMPTIONABSLTAMOUNT COMMENT 'Withholding tax exemption absolute amount',
	VALNDIFFABSLTAMTINCOCODECRCY COMMENT 'Valuation difference absolute amount in company code currency',
	VALNDIFFABSLTAMTINADDLCRCY1 COMMENT 'Valuation difference absolute amount in first additional currency',
	VALNDIFFABSLTAMTINADDLCRCY2 COMMENT 'Valuation difference absolute amount in second additional currency',
	UNADJUSTEDDEBITCREDITCODE COMMENT 'Original debit/credit code before adjustments',
	RECEIVABLEFINANCINGSTATUS COMMENT 'Status of receivable financing',
	NUMBEROFITEMS COMMENT 'Number of items in the document',
	EARMARKEDFUNDS COMMENT 'Earmarked funds identifier',
	EARMARKEDFUNDSITEM COMMENT 'Earmarked funds item',
	IN_GSTPARTNER COMMENT 'India GST partner identifier',
	IN_GSTPLACEOFSUPPLY COMMENT 'India GST place of supply',
	IN_HSNORSACCODE COMMENT 'India HSN or SAC code for GST',
	IN_INVOICEREFERENCENUMBER COMMENT 'India invoice reference number',
	ORIGLTAXBASEAMOUNTINCOCODECRCY COMMENT 'Original tax base amount in company code currency',
	ORIGINALTAXBASEAMTINADDLCRCY1 COMMENT 'Original tax base amount in first additional currency',
	ORIGINALTAXBASEAMTINADDLCRCY2 COMMENT 'Original tax base amount in second additional currency',
	DIGITALPAYMENTTYPE COMMENT 'Digital payment type',
	PAYMENTBYDIGITALPAYMENTSERVICE COMMENT 'Payment by digital payment service flag',
	GLACCOUNTAUTHORIZATIONGROUP COMMENT 'GL account authorization group',
	SUPPLIERBASICAUTHORIZATIONGRP COMMENT 'Supplier basic authorization group',
	CUSTOMERBASICAUTHORIZATIONGRP COMMENT 'Customer basic authorization group',
	ACCTGDOCTYPEAUTHORIZATIONGROUP COMMENT 'Accounting document type authorization group',
	ORDERTYPE COMMENT 'Order type code',
	SALESORDERTYPE COMMENT 'Sales order type',
	ASSETCLASS COMMENT 'Asset class for fixed asset categorization',
	OPERATIONALACCTGDOCITEMOID COMMENT 'Operational accounting document item object ID'
) as
SELECT * FROM SAP_BDC_DEMO_ENTRY_VIEW_JOURNAL_ENTRY.BDCCONNECT.OPERATIONALACCTGDOCITEM;
create or replace view SAP_FINANCE_360.SAP_BDC_L1.PROFITCENTER(
	CONTROLLINGAREA COMMENT 'Controlling area for cost accounting',
	PROFITCENTER COMMENT 'Profit center identifier',
	VALIDITYENDDATE COMMENT 'End date of the profit center validity period',
	PROFITCTRRESPONSIBLEPERSONNAME COMMENT 'Name of the person responsible for the profit center',
	COMPANYCODE COMMENT 'SAP company code',
	PROFITCTRRESPONSIBLEUSER COMMENT 'SAP user responsible for the profit center',
	VALIDITYSTARTDATE COMMENT 'Start date of the profit center validity period',
	DEPARTMENT COMMENT 'Organizational department',
	PROFITCENTERSTANDARDHIERARCHY COMMENT 'Standard hierarchy for profit center reporting',
	SEGMENT COMMENT 'Segment for external segment reporting',
	PROFITCENTERISBLOCKED COMMENT 'Whether the profit center is blocked for postings',
	FORMULAPLANNINGTEMPLATE COMMENT 'Formula planning template assignment',
	FORMOFADDRESS COMMENT 'Form of address for profit center contact',
	ADDRESSNAME COMMENT 'Primary address name',
	ADDITIONALNAME COMMENT 'Additional name field',
	PROFITCENTERADDRNAME3 COMMENT 'Address name field 3',
	PROFITCENTERADDRNAME4 COMMENT 'Address name field 4',
	STREETADDRESSNAME COMMENT 'Street address',
	POBOX COMMENT 'Post office box number',
	CITYNAME COMMENT 'City name',
	POSTALCODE COMMENT 'Postal/ZIP code',
	POBOXPOSTALCODE COMMENT 'PO box postal code',
	DISTRICT COMMENT 'District name',
	COUNTRY COMMENT 'Country code',
	REGION COMMENT 'Region/state code',
	TAXJURISDICTION COMMENT 'Tax jurisdiction code',
	LANGUAGE COMMENT 'Language key',
	PHONENUMBER1 COMMENT 'Primary phone number',
	PHONENUMBER2 COMMENT 'Secondary phone number',
	TELEBOXNUMBER COMMENT 'Telebox number',
	TELEXNUMBER COMMENT 'Telex number',
	FAXNUMBER COMMENT 'Fax number',
	TELETEXNUMBER COMMENT 'Teletex number',
	DATACOMMUNICATIONPHONENUMBER COMMENT 'Data communication phone number',
	PROFITCENTERPRINTERNAME COMMENT 'Printer name for the profit center',
	PROFITCENTERCREATEDBYUSER COMMENT 'User who created the profit center',
	PROFITCENTERCREATIONDATE COMMENT 'Date the profit center was created',
	LOGICALSYSTEM COMMENT 'SAP logical system identifier',
	_PRFTCTRCOMPANYCODEASSIGNMENT COMMENT 'Internal profit center company code assignment',
	_PROFITCENTERHIERARCHYNODE COMMENT 'Profit center hierarchy node assignment',
	_TEXT COMMENT 'Profit center text description'
) as
SELECT * FROM SAP_BDC_DEMO_PROFIT_CENTER.BDCCONNECT.PROFITCENTER;
create or replace view SAP_FINANCE_360.SAP_BDC_L1.SUPPLIERINVOICE(
	SUPPLIERINVOICE COMMENT 'Supplier invoice document number',
	FISCALYEAR COMMENT 'Fiscal year of the supplier invoice',
	COMPANYCODE COMMENT 'SAP company code',
	DOCUMENTDATE COMMENT 'Date on the supplier invoice document',
	POSTINGDATE COMMENT 'Date the invoice was posted to the ledger',
	SUPPLIERINVOICEIDBYINVCGPARTY COMMENT 'Invoice ID assigned by the invoicing party',
	INVOICINGPARTY COMMENT 'Vendor/supplier who issued the invoice',
	ISINVOICE COMMENT 'Whether this record represents an invoice (vs credit memo)',
	DOCUMENTCURRENCY COMMENT 'Currency of the invoice document',
	INVOICEGROSSAMOUNT COMMENT 'Gross amount of the supplier invoice',
	SUPLRINVCAUTOMREDUCEDAMOUNT COMMENT 'Automatically reduced amount on the supplier invoice',
	UNPLANNEDDELIVERYCOST COMMENT 'Unplanned delivery cost amount',
	DOCUMENTHEADERTEXT COMMENT 'Free-text description in the invoice header',
	SUPPLIERINVOICEORIGIN COMMENT 'Origin of the supplier invoice (e.g. manual, EDI)',
	SUPLRINVCMANUALLYREDUCEDAMOUNT COMMENT 'Manually reduced amount on the supplier invoice',
	UNPLANNEDDELIVERYCOSTTAXCODE COMMENT 'Tax code for unplanned delivery costs',
	SUPPLIERINVOICESTATUS COMMENT 'Processing status of the supplier invoice (P/A/C/X)',
	REVERSEDOCUMENT COMMENT 'Reversal document number',
	REVERSEDOCUMENTFISCALYEAR COMMENT 'Fiscal year of the reversal document',
	_SUPPLIERINVOICEITEMDEX COMMENT 'Internal supplier invoice item index'
) as
SELECT * FROM SAP_BDC_DEMO_SUPPLIER_INVOICE.BDCCONNECT.SUPPLIERINVOICE;
