-- =============================================================================
-- SAP Finance 360 — Pipeline 2: Streams + Tasks (CDC-driven incremental)
-- =============================================================================
-- Demonstrates Snowflake's native change data capture with Streams and
-- event-driven task execution for real-time silver-to-gold processing.
--
-- Architecture:
--   L0 base tables → Streams (CDC) → Task Graph (MERGE) → STREAM_GOLD tables
-- =============================================================================

USE ROLE ACCOUNTADMIN;
USE DATABASE SAP_FINANCE_360;

-- =============================================================================
-- 1. OUTPUT SCHEMA
-- =============================================================================
CREATE SCHEMA IF NOT EXISTS SAP_FINANCE_360.STREAM_GOLD
  COMMENT = 'Gold tables maintained by Streams + Tasks (CDC-driven incremental pipeline)';

-- =============================================================================
-- 2. ENABLE CHANGE TRACKING ON L0 BASE TABLES
-- =============================================================================
ALTER TABLE SAP_FINANCE_360.SAP_BDC_L0.OPERATIONALACCTGDOCITEM 
  SET CHANGE_TRACKING = TRUE;

ALTER TABLE SAP_FINANCE_360.SAP_BDC_L0.SUPPLIERINVOICE 
  SET CHANGE_TRACKING = TRUE;

-- =============================================================================
-- 3. CREATE STREAMS (capture inserts/updates/deletes on L0)
-- =============================================================================
CREATE OR REPLACE STREAM SAP_FINANCE_360.STREAM_GOLD.STREAM_GL_LINE_ITEMS
  ON TABLE SAP_FINANCE_360.SAP_BDC_L0.OPERATIONALACCTGDOCITEM
  APPEND_ONLY = TRUE
  COMMENT = 'Captures new GL line items arriving in L0';

CREATE OR REPLACE STREAM SAP_FINANCE_360.STREAM_GOLD.STREAM_SUPPLIER_INVOICES
  ON TABLE SAP_FINANCE_360.SAP_BDC_L0.SUPPLIERINVOICE
  APPEND_ONLY = TRUE
  COMMENT = 'Captures new supplier invoices arriving in L0';

-- =============================================================================
-- 4. CREATE GOLD TARGET TABLES
-- =============================================================================
CREATE OR REPLACE TABLE SAP_FINANCE_360.STREAM_GOLD.GL_BALANCE (
    COMPANYCODE VARCHAR(4),
    GLACCOUNT VARCHAR(10),
    FISCALYEAR VARCHAR(4),
    FISCALPERIOD VARCHAR(3),
    DEBITCREDITCODE VARCHAR(1),
    AMOUNT NUMBER(18,2),
    LINE_COUNT NUMBER(10,0),
    LAST_UPDATED TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
) COMMENT = 'GL balance aggregated by period - maintained by stream/task pipeline';

CREATE OR REPLACE TABLE SAP_FINANCE_360.STREAM_GOLD.PNL_SUMMARY (
    COMPANYCODE VARCHAR(4),
    FISCALYEAR VARCHAR(4),
    FISCALPERIOD VARCHAR(3),
    COMPANYCODECURRENCY VARCHAR(5),
    REVENUE NUMBER(18,2),
    EXPENSES NUMBER(18,2),
    NET_INCOME NUMBER(18,2),
    DOCUMENT_COUNT NUMBER(10,0),
    LINE_ITEM_COUNT NUMBER(10,0),
    LAST_UPDATED TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
) COMMENT = 'P&L summary by period - maintained by stream/task pipeline';

CREATE OR REPLACE TABLE SAP_FINANCE_360.STREAM_GOLD.EXPENSE_BY_COSTCENTER (
    COMPANYCODE VARCHAR(4),
    COSTCENTER VARCHAR(10),
    DEPARTMENT VARCHAR(100),
    PROFITCENTER VARCHAR(10),
    GLACCOUNT VARCHAR(10),
    FISCALYEAR VARCHAR(4),
    FISCALPERIOD VARCHAR(3),
    EXPENSE_AMOUNT NUMBER(18,2),
    LINE_COUNT NUMBER(10,0),
    LAST_UPDATED TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
) COMMENT = 'Expense by cost center - maintained by stream/task pipeline';

CREATE OR REPLACE TABLE SAP_FINANCE_360.STREAM_GOLD.AP_AGING (
    COMPANYCODE VARCHAR(4),
    VENDOR VARCHAR(20),
    DOCUMENTCURRENCY VARCHAR(5),
    FISCALYEAR VARCHAR(4),
    DOCUMENTDATE DATE,
    POSTINGDATE DATE,
    INVOICEGROSSAMOUNT NUMBER(18,2),
    SUPPLIERINVOICESTATUS VARCHAR(5),
    DAYS_OUTSTANDING NUMBER(5,0),
    AGING_BUCKET VARCHAR(20),
    LAST_UPDATED TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
) COMMENT = 'AP aging buckets - maintained by stream/task pipeline';

-- =============================================================================
-- 5. INITIAL LOAD (seed gold tables from current L1 data)
-- =============================================================================
INSERT INTO SAP_FINANCE_360.STREAM_GOLD.GL_BALANCE
SELECT COMPANYCODE, GLACCOUNT, FISCALYEAR, FISCALPERIOD, DEBITCREDITCODE,
       SUM(AMOUNTINCOMPANYCODECURRENCY), COUNT(*), CURRENT_TIMESTAMP()
FROM SAP_FINANCE_360.SAP_BDC_L1.OPERATIONALACCTGDOCITEM
GROUP BY COMPANYCODE, GLACCOUNT, FISCALYEAR, FISCALPERIOD, DEBITCREDITCODE;

INSERT INTO SAP_FINANCE_360.STREAM_GOLD.PNL_SUMMARY
SELECT COMPANYCODE, FISCALYEAR, FISCALPERIOD, COMPANYCODECURRENCY,
       SUM(CASE WHEN GLACCOUNT LIKE '4%' AND DEBITCREDITCODE = 'H' THEN ABS(AMOUNTINCOMPANYCODECURRENCY) ELSE 0 END),
       SUM(CASE WHEN (GLACCOUNT LIKE '5%' OR GLACCOUNT LIKE '6%') AND DEBITCREDITCODE = 'S' THEN ABS(AMOUNTINCOMPANYCODECURRENCY) ELSE 0 END),
       SUM(CASE WHEN GLACCOUNT LIKE '4%' AND DEBITCREDITCODE = 'H' THEN ABS(AMOUNTINCOMPANYCODECURRENCY) ELSE 0 END)
       - SUM(CASE WHEN (GLACCOUNT LIKE '5%' OR GLACCOUNT LIKE '6%') AND DEBITCREDITCODE = 'S' THEN ABS(AMOUNTINCOMPANYCODECURRENCY) ELSE 0 END),
       COUNT(DISTINCT ACCOUNTINGDOCUMENT), COUNT(*), CURRENT_TIMESTAMP()
FROM SAP_FINANCE_360.SAP_BDC_L1.OPERATIONALACCTGDOCITEM
GROUP BY COMPANYCODE, FISCALYEAR, FISCALPERIOD, COMPANYCODECURRENCY;

INSERT INTO SAP_FINANCE_360.STREAM_GOLD.EXPENSE_BY_COSTCENTER
SELECT li.COMPANYCODE, li.COSTCENTER, cc.DEPARTMENT, li.PROFITCENTER, li.GLACCOUNT,
       li.FISCALYEAR, li.FISCALPERIOD, SUM(ABS(li.AMOUNTINCOMPANYCODECURRENCY)), COUNT(*), CURRENT_TIMESTAMP()
FROM SAP_FINANCE_360.SAP_BDC_L1.OPERATIONALACCTGDOCITEM li
LEFT JOIN SAP_FINANCE_360.SAP_BDC_L1.COSTCENTER cc
    ON li.COSTCENTER = cc.COSTCENTER AND li.COMPANYCODE = cc.COMPANYCODE
WHERE li.DEBITCREDITCODE = 'S' AND (li.GLACCOUNT LIKE '5%' OR li.GLACCOUNT LIKE '6%') AND li.COSTCENTER != ''
GROUP BY li.COMPANYCODE, li.COSTCENTER, cc.DEPARTMENT, li.PROFITCENTER, li.GLACCOUNT, li.FISCALYEAR, li.FISCALPERIOD;

INSERT INTO SAP_FINANCE_360.STREAM_GOLD.AP_AGING
SELECT COMPANYCODE, INVOICINGPARTY, DOCUMENTCURRENCY, FISCALYEAR, DOCUMENTDATE, POSTINGDATE,
       INVOICEGROSSAMOUNT, SUPPLIERINVOICESTATUS,
       DATEDIFF('day', POSTINGDATE, (SELECT MAX(POSTINGDATE) FROM SAP_FINANCE_360.SAP_BDC_L1.SUPPLIERINVOICE)),
       CASE
           WHEN DATEDIFF('day', POSTINGDATE, (SELECT MAX(POSTINGDATE) FROM SAP_FINANCE_360.SAP_BDC_L1.SUPPLIERINVOICE)) <= 30 THEN 'Current'
           WHEN DATEDIFF('day', POSTINGDATE, (SELECT MAX(POSTINGDATE) FROM SAP_FINANCE_360.SAP_BDC_L1.SUPPLIERINVOICE)) <= 60 THEN '31-60 Days'
           WHEN DATEDIFF('day', POSTINGDATE, (SELECT MAX(POSTINGDATE) FROM SAP_FINANCE_360.SAP_BDC_L1.SUPPLIERINVOICE)) <= 90 THEN '61-90 Days'
           ELSE '90+ Days'
       END,
       CURRENT_TIMESTAMP()
FROM SAP_FINANCE_360.SAP_BDC_L1.SUPPLIERINVOICE
WHERE ISINVOICE = TRUE;

-- =============================================================================
-- 6. TASK GRAPH — Event-driven incremental processing
-- =============================================================================

-- Root task: fires when GL stream has data
CREATE OR REPLACE TASK SAP_FINANCE_360.STREAM_GOLD.TASK_PROCESS_GL_BALANCE
  WAREHOUSE = LOAD_WH
  SCHEDULE = '5 MINUTES'
  COMMENT = 'Root task: processes new GL line items into GL_BALANCE when stream has data'
  WHEN SYSTEM$STREAM_HAS_DATA('SAP_FINANCE_360.STREAM_GOLD.STREAM_GL_LINE_ITEMS')
AS
MERGE INTO SAP_FINANCE_360.STREAM_GOLD.GL_BALANCE tgt
USING (
    SELECT COMPANYCODE, GLACCOUNT, FISCALYEAR, FISCALPERIOD, DEBITCREDITCODE,
           SUM(AMOUNTINCOMPANYCODECURRENCY) AS AMOUNT,
           COUNT(*) AS LINE_COUNT
    FROM SAP_FINANCE_360.STREAM_GOLD.STREAM_GL_LINE_ITEMS
    GROUP BY COMPANYCODE, GLACCOUNT, FISCALYEAR, FISCALPERIOD, DEBITCREDITCODE
) src
ON tgt.COMPANYCODE = src.COMPANYCODE
   AND tgt.GLACCOUNT = src.GLACCOUNT
   AND tgt.FISCALYEAR = src.FISCALYEAR
   AND tgt.FISCALPERIOD = src.FISCALPERIOD
   AND tgt.DEBITCREDITCODE = src.DEBITCREDITCODE
WHEN MATCHED THEN UPDATE SET
    tgt.AMOUNT = tgt.AMOUNT + src.AMOUNT,
    tgt.LINE_COUNT = tgt.LINE_COUNT + src.LINE_COUNT,
    tgt.LAST_UPDATED = CURRENT_TIMESTAMP()
WHEN NOT MATCHED THEN INSERT
    (COMPANYCODE, GLACCOUNT, FISCALYEAR, FISCALPERIOD, DEBITCREDITCODE, AMOUNT, LINE_COUNT, LAST_UPDATED)
    VALUES (src.COMPANYCODE, src.GLACCOUNT, src.FISCALYEAR, src.FISCALPERIOD, src.DEBITCREDITCODE,
            src.AMOUNT, src.LINE_COUNT, CURRENT_TIMESTAMP());

-- Child task 1: rebuild PNL after GL processes
CREATE OR REPLACE TASK SAP_FINANCE_360.STREAM_GOLD.TASK_PROCESS_PNL
  WAREHOUSE = LOAD_WH
  COMMENT = 'Rebuilds P&L summary after GL balance updates'
  AFTER SAP_FINANCE_360.STREAM_GOLD.TASK_PROCESS_GL_BALANCE
AS
BEGIN
  TRUNCATE TABLE SAP_FINANCE_360.STREAM_GOLD.PNL_SUMMARY;
  INSERT INTO SAP_FINANCE_360.STREAM_GOLD.PNL_SUMMARY
  SELECT COMPANYCODE, FISCALYEAR, FISCALPERIOD, COMPANYCODECURRENCY,
         SUM(CASE WHEN GLACCOUNT LIKE '4%' AND DEBITCREDITCODE = 'H' THEN ABS(AMOUNTINCOMPANYCODECURRENCY) ELSE 0 END),
         SUM(CASE WHEN (GLACCOUNT LIKE '5%' OR GLACCOUNT LIKE '6%') AND DEBITCREDITCODE = 'S' THEN ABS(AMOUNTINCOMPANYCODECURRENCY) ELSE 0 END),
         SUM(CASE WHEN GLACCOUNT LIKE '4%' AND DEBITCREDITCODE = 'H' THEN ABS(AMOUNTINCOMPANYCODECURRENCY) ELSE 0 END)
         - SUM(CASE WHEN (GLACCOUNT LIKE '5%' OR GLACCOUNT LIKE '6%') AND DEBITCREDITCODE = 'S' THEN ABS(AMOUNTINCOMPANYCODECURRENCY) ELSE 0 END),
         COUNT(DISTINCT ACCOUNTINGDOCUMENT), COUNT(*), CURRENT_TIMESTAMP()
  FROM SAP_FINANCE_360.SAP_BDC_L0.OPERATIONALACCTGDOCITEM
  GROUP BY COMPANYCODE, FISCALYEAR, FISCALPERIOD, COMPANYCODECURRENCY;
END;

-- Child task 2: rebuild expenses after GL processes
CREATE OR REPLACE TASK SAP_FINANCE_360.STREAM_GOLD.TASK_PROCESS_EXPENSES
  WAREHOUSE = LOAD_WH
  COMMENT = 'Rebuilds expense by cost center after GL balance updates'
  AFTER SAP_FINANCE_360.STREAM_GOLD.TASK_PROCESS_GL_BALANCE
AS
BEGIN
  TRUNCATE TABLE SAP_FINANCE_360.STREAM_GOLD.EXPENSE_BY_COSTCENTER;
  INSERT INTO SAP_FINANCE_360.STREAM_GOLD.EXPENSE_BY_COSTCENTER
  SELECT li.COMPANYCODE, li.COSTCENTER, cc.DEPARTMENT, li.PROFITCENTER, li.GLACCOUNT,
         li.FISCALYEAR, li.FISCALPERIOD, SUM(ABS(li.AMOUNTINCOMPANYCODECURRENCY)), COUNT(*), CURRENT_TIMESTAMP()
  FROM SAP_FINANCE_360.SAP_BDC_L0.OPERATIONALACCTGDOCITEM li
  LEFT JOIN SAP_FINANCE_360.SAP_BDC_L1.COSTCENTER cc
      ON li.COSTCENTER = cc.COSTCENTER AND li.COMPANYCODE = cc.COMPANYCODE
  WHERE li.DEBITCREDITCODE = 'S' AND (li.GLACCOUNT LIKE '5%' OR li.GLACCOUNT LIKE '6%') AND li.COSTCENTER != ''
  GROUP BY li.COMPANYCODE, li.COSTCENTER, cc.DEPARTMENT, li.PROFITCENTER, li.GLACCOUNT, li.FISCALYEAR, li.FISCALPERIOD;
END;

-- Separate root task for AP aging (triggered by supplier invoice stream)
CREATE OR REPLACE TASK SAP_FINANCE_360.STREAM_GOLD.TASK_PROCESS_AP_AGING
  WAREHOUSE = LOAD_WH
  SCHEDULE = '5 MINUTES'
  COMMENT = 'Processes new supplier invoices into AP aging when stream has data'
  WHEN SYSTEM$STREAM_HAS_DATA('SAP_FINANCE_360.STREAM_GOLD.STREAM_SUPPLIER_INVOICES')
AS
BEGIN
  TRUNCATE TABLE SAP_FINANCE_360.STREAM_GOLD.AP_AGING;
  INSERT INTO SAP_FINANCE_360.STREAM_GOLD.AP_AGING
  SELECT COMPANYCODE, INVOICINGPARTY, DOCUMENTCURRENCY, FISCALYEAR, DOCUMENTDATE, POSTINGDATE,
         INVOICEGROSSAMOUNT, SUPPLIERINVOICESTATUS,
         DATEDIFF('day', POSTINGDATE, (SELECT MAX(POSTINGDATE) FROM SAP_FINANCE_360.SAP_BDC_L0.SUPPLIERINVOICE)),
         CASE
             WHEN DATEDIFF('day', POSTINGDATE, (SELECT MAX(POSTINGDATE) FROM SAP_FINANCE_360.SAP_BDC_L0.SUPPLIERINVOICE)) <= 30 THEN 'Current'
             WHEN DATEDIFF('day', POSTINGDATE, (SELECT MAX(POSTINGDATE) FROM SAP_FINANCE_360.SAP_BDC_L0.SUPPLIERINVOICE)) <= 60 THEN '31-60 Days'
             WHEN DATEDIFF('day', POSTINGDATE, (SELECT MAX(POSTINGDATE) FROM SAP_FINANCE_360.SAP_BDC_L0.SUPPLIERINVOICE)) <= 90 THEN '61-90 Days'
             ELSE '90+ Days'
         END,
         CURRENT_TIMESTAMP()
  FROM SAP_FINANCE_360.SAP_BDC_L0.SUPPLIERINVOICE
  WHERE ISINVOICE = TRUE;
END;

-- =============================================================================
-- 7. RESUME TASKS (activate the pipeline)
-- =============================================================================
ALTER TASK SAP_FINANCE_360.STREAM_GOLD.TASK_PROCESS_EXPENSES RESUME;
ALTER TASK SAP_FINANCE_360.STREAM_GOLD.TASK_PROCESS_PNL RESUME;
ALTER TASK SAP_FINANCE_360.STREAM_GOLD.TASK_PROCESS_GL_BALANCE RESUME;
ALTER TASK SAP_FINANCE_360.STREAM_GOLD.TASK_PROCESS_AP_AGING RESUME;

-- =============================================================================
-- DEMO: Insert test data to trigger streams/tasks
-- After running this, check task history in Snowsight to see the pipeline fire.
-- =============================================================================
-- INSERT INTO SAP_FINANCE_360.SAP_BDC_L0.OPERATIONALACCTGDOCITEM
-- (COMPANYCODE, ACCOUNTINGDOCUMENT, FISCALYEAR, ACCOUNTINGDOCUMENTITEM, GLACCOUNT,
--  POSTINGDATE, AMOUNTINCOMPANYCODECURRENCY, DEBITCREDITCODE, COSTCENTER, PROFITCENTER,
--  COMPANYCODECURRENCY, FISCALPERIOD)
-- VALUES
-- ('1000', '9900001', '2025', '001', '50100000', '2025-07-01', 15000.00, 'S', 'CC1010', 'PC2010', 'USD', '007'),
-- ('1000', '9900001', '2025', '002', '11000000', '2025-07-01', -15000.00, 'H', '', '', 'USD', '007');
